export enum DataType {
  JSON = 'json',
  CSV = 'csv',
}

export enum OutputSize {
  COMPACT = 'compact',
  FULL = 'full',
}

export enum AllioQueryFunction {
  TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY',
  TIME_SERIES_DAILY = 'TIME_SERIES_DAILY',
  TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY',
  TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY',
  TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED',
  GLOBAL_QUOTE = 'GLOBAL_QUOTE',
  SYMBOL_SEARCH = 'SYMBOL_SEARCH',
  MARKET_STATUS = 'MARKET_STATUS',
}
