version: '3.8'

services:
    postgres:
        container_name: allio-test-postgres
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ../../db-data/postgresql:/data/postgres
        env_file:
            - docker.env